In [2]:
import numpy as np

## Dtype

In [3]:
arr_1 = np.array([1,2,3], dtype=np.float32)
arr_1

array([1., 2., 3.], dtype=float32)

In [4]:
lst = [1,2,3]
A = np.array(lst, dtype=np.int16)
A

array([1, 2, 3], dtype=int16)

## Structured Arrays

In [5]:
density_type = np.dtype([ ("density", np.int32)])
densities = np.array( [393, 337, 256] , dtype=density_type)

print("Estructured array\n",densities)
print("\nThe internal representation\n",repr(densities))
print("\nDensity\n", densities["density"])

Estructured array
 [(393,) (337,) (256,)]

The internal representation
 array([(393,), (337,), (256,)], dtype=[('density', '<i4')])

Density
 [393 337 256]


In [6]:
dt = np.dtype([
    ('country', 'U20'), 
    ('density', 'i4'), 
    ('area', 'i4'), 
    ('population', 'i4')
])

population_table_2025 = np.array([
    ('Netherlands', 544, 33720, 18_346_819),
    ('Belgium', 383, 30510, 11_700_000),
    ('United Kingdom', 287, 243610, 69_800_000),
    ('Germany', 241, 348560, 84_075_075),
    ('Liechtenstein', 238, 160, 38_080),
    ('Italy', 197, 301230, 59_400_000),
    ('Switzerland', 219, 41290, 9_050_000),
    ('Luxembourg', 253, 2586, 654_000),
    ('France', 122, 547030, 66_700_000),
    ('Austria', 109, 83858, 9_140_000),
    ('Greece', 81, 131940, 10_700_000),
    ('Ireland', 77, 70280, 5_400_000),
    ('Sweden', 26, 449964, 10_300_000),
    ('Finland', 18, 338424, 6_100_000),
    ('Norway', 15, 385252, 5_800_000)
], dtype=dt)

print(population_table_2025[:4])

[('Netherlands', 544,  33720, 18346819) ('Belgium', 383,  30510, 11700000)
 ('United Kingdom', 287, 243610, 69800000)
 ('Germany', 241, 348560, 84075075)]


## Input and output of structured array

In [7]:
np.savetxt("population_table_2025.csv", population_table_2025, fmt="%s;%d;%d;%d", delimiter=";" )

In [8]:
dt = np.dtype([("country",'U20'),("density",'i4'),("area",'i4'),("population",'i4')])
df = np.genfromtxt("population_table_2025.csv", dtype=dt, delimiter=";")
df

array([('Netherlands', 544,  33720, 18346819),
       ('Belgium', 383,  30510, 11700000),
       ('United Kingdom', 287, 243610, 69800000),
       ('Germany', 241, 348560, 84075075),
       ('Liechtenstein', 238,    160,    38080),
       ('Italy', 197, 301230, 59400000),
       ('Switzerland', 219,  41290,  9050000),
       ('Luxembourg', 253,   2586,   654000),
       ('France', 122, 547030, 66700000),
       ('Austria', 109,  83858,  9140000),
       ('Greece',  81, 131940, 10700000),
       ('Ireland',  77,  70280,  5400000),
       ('Sweden',  26, 449964, 10300000),
       ('Finland',  18, 338424,  6100000),
       ('Norway',  15, 385252,  5800000)],
      dtype=[('country', '<U20'), ('density', '<i4'), ('area', '<i4'), ('population', '<i4')])

## Operations

In [9]:
population_table_1995 = np.array([
    ('Netherlands', 462, 33720, 15_565_032),
    ('Belgium', 332, 30510, 10_137_265),
    ('United Kingdom', 239, 243610, 58_154_634),
    ('Germany', 235, 348560, 82_019_890),
    ('Liechtenstein', 193, 160, 30_886),
    ('Italy', 189, 301230, 56_885_126),
    ('Switzerland', 171, 41290, 7_040_477),
    ('Luxembourg', 158, 2586, 408_227),
    ('France', 106, 547030, 58_192_203),
    ('Austria', 95, 83858, 7_943_489),
    ('Greece', 80, 131940, 10_519_234),
    ('Ireland', 51, 70280, 3_610_697),
    ('Sweden', 20, 449964, 8_826_301),
    ('Finland', 15, 338424, 5_107_922),
    ('Norway', 11, 385252, 4_358_992)
], dtype=dt)

area_changed = population_table_2025["area"] != population_table_1995["area"] 
print(population_table_2025["area"][area_changed])

population_changed = population_table_2025["population"] != population_table_1995["area"]
print(population_changed)
print(population_table_2025["country"][population_changed])

population_diff = population_table_2025["population"] - population_table_1995["population"]
print(population_diff)

[]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
['Netherlands' 'Belgium' 'United Kingdom' 'Germany' 'Liechtenstein'
 'Italy' 'Switzerland' 'Luxembourg' 'France' 'Austria' 'Greece' 'Ireland'
 'Sweden' 'Finland' 'Norway']
[ 2781787  1562735 11645366  2055185     7194  2514874  2009523   245773
  8507797  1196511   180766  1789303  1473699   992078  1441008]


In [10]:
for country, difference in zip(population_table_2025["country"], population_diff):
    print(f"{country:20}: \t{difference:>12}")

Netherlands         : 	     2781787
Belgium             : 	     1562735
United Kingdom      : 	    11645366
Germany             : 	     2055185
Liechtenstein       : 	        7194
Italy               : 	     2514874
Switzerland         : 	     2009523
Luxembourg          : 	      245773
France              : 	     8507797
Austria             : 	     1196511
Greece              : 	      180766
Ireland             : 	     1789303
Sweden              : 	     1473699
Finland             : 	      992078
Norway              : 	     1441008


In [11]:
dt = np.dtype([
    ("country", 'U20'),("density",'i4'),("area",'i4'),("population",'i4'),("difference",'i4') 
])
population_table_2025_with_difference = np.array([
    (country, density, area, population, difference) for country, density, area, population, difference in zip(
        population_table_2025["country"],
        population_table_2025["density"],
        population_table_2025["area"],
        population_table_2025["population"],
        population_diff
    )
],dtype = dt)
print(population_table_2025_with_difference)

[('Netherlands', 544,  33720, 18346819,  2781787)
 ('Belgium', 383,  30510, 11700000,  1562735)
 ('United Kingdom', 287, 243610, 69800000, 11645366)
 ('Germany', 241, 348560, 84075075,  2055185)
 ('Liechtenstein', 238,    160,    38080,     7194)
 ('Italy', 197, 301230, 59400000,  2514874)
 ('Switzerland', 219,  41290,  9050000,  2009523)
 ('Luxembourg', 253,   2586,   654000,   245773)
 ('France', 122, 547030, 66700000,  8507797)
 ('Austria', 109,  83858,  9140000,  1196511)
 ('Greece',  81, 131940, 10700000,   180766)
 ('Ireland',  77,  70280,  5400000,  1789303)
 ('Sweden',  26, 449964, 10300000,  1473699)
 ('Finland',  18, 338424,  6100000,   992078)
 ('Norway',  15, 385252,  5800000,  1441008)]


## Using Scalars

In [12]:
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
lst = np.array(lst)

print(lst + 1)
print(lst - 1)
print(lst * 2)
print(lst / 2)

[ 3.    4.    8.9   4.3   7.9   1.11 11.3  13.9 ]
[ 1.    2.    6.9   2.3   5.9  -0.89  9.3  11.9 ]
[ 4.    6.   15.8   6.6  13.8   0.22 20.6  25.8 ]
[1.    1.5   3.95  1.65  3.45  0.055 5.15  6.45 ]


## Arithmetic Operations with two Arrays

In [13]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))

print(A + B)
print(A * (B+1))

[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


## Matrix Multiplication

In [14]:
x = np.array([3, -2])
y = np.array([-4, 1])

print(np.dot(x, y))

-14


In [15]:
A = np.array([ [1, 2, 3], 
               [3, 2, 1] ])
B = np.array([ [2, 3, 4, -2], 
               [1, -1, 2, 3],
               [1, 2, 3, 0] ])

print(np.dot(A, B))

[[ 7  7 17  4]
 [ 9  9 19  0]]


In [16]:
X = np.array( [[[3, 1, 2],
                [4, 2, 2],
                [2, 4, 1]],

               [[3, 2, 2],
                [4, 4, 3],
                [4, 1, 1]],

               [[2, 2, 1],
                [3, 1, 3],
                [3, 2, 3]]])

Y = np.array( [[[2, 3, 1],
                [2, 2, 4],
                [3, 4, 4]],
            
               [[1, 4, 1],
                [4, 1, 2],
                [4, 1, 2]],
            
               [[1, 2, 3],
                [4, 1, 1],
                [3, 1, 4]]])

print(X, Y)

[[[3 1 2]
  [4 2 2]
  [2 4 1]]

 [[3 2 2]
  [4 4 3]
  [4 1 1]]

 [[2 2 1]
  [3 1 3]
  [3 2 3]]] [[[2 3 1]
  [2 2 4]
  [3 4 4]]

 [[1 4 1]
  [4 1 2]
  [4 1 2]]

 [[1 2 3]
  [4 1 1]
  [3 1 4]]]


In [17]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])

matA = np.asmatrix(A)
matB = np.asmatrix(B)

print(matA * matB)

[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


## Comparison opeators

In [18]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])

A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

## Logical operators

In [19]:
a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])

print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


## Broadcasting

In [20]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])

print(A * B)
print(A + B)
print(B[:, np.newaxis])
print(np.array([[1,2,3]]).transpose())
print(np.tile(B, (3,1)))

[[11 24 39]
 [21 44 69]
 [31 64 99]]
[[12 14 16]
 [22 24 26]
 [32 34 36]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Distance Matrix

In [21]:
cities = ["Barcelona", "Berlin", "Brussels", "Bucharest",
          "Budapest", "Copenhagen", "Dublin", "Hamburg", "Istanbul",
          "Kiev", "London", "Madrid", "Milan", "Moscow", "Munich",
          "Paris", "Prague", "Rome", "Saint Petersburg", 
          "Stockholm", "Vienna", "Warsaw"]

dist2barcelona = [0,  1498, 1063, 1968, 
                  1498, 1758, 1469, 1472, 2230, 
                  2391, 1138, 505, 725, 3007, 1055, 
                  833, 1354, 857, 2813, 
                  2277, 1347, 1862]

dist = np.array(dist2barcelona[:12])
print(dist)
print( np.abs(dist - dist[:, np.newaxis]) )

[   0 1498 1063 1968 1498 1758 1469 1472 2230 2391 1138  505]
[[   0 1498 1063 1968 1498 1758 1469 1472 2230 2391 1138  505]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1063  435    0  905  435  695  406  409 1167 1328   75  558]
 [1968  470  905    0  470  210  499  496  262  423  830 1463]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1758  260  695  210  260    0  289  286  472  633  620 1253]
 [1469   29  406  499   29  289    0    3  761  922  331  964]
 [1472   26  409  496   26  286    3    0  758  919  334  967]
 [2230  732 1167  262  732  472  761  758    0  161 1092 1725]
 [2391  893 1328  423  893  633  922  919  161    0 1253 1886]
 [1138  360   75  830  360  620  331  334 1092 1253    0  633]
 [ 505  993  558 1463  993 1253  964  967 1725 1886  633    0]]


## 3-dimensional broadcasting

In [24]:
A = np.array([ [[3, 4, 7], [5, 0, -1] , [2, 1, 5]],
      [[1, 0, -1], [8, 2, 4], [5, 2, 1]],
      [[2, 1, 3], [1, 9, 4], [5, -2, 4]]])

B = np.array([1, 2, 3])
print(B.shape)
print(B, "\n")

B = B[np.newaxis, :]
print(B.shape)
print(B, "\n")

B = np.concatenate((B, B, B)).transpose()
print(B.shape)
print(B, "\n")

B = B[:, np.newaxis]
print(B.shape)
print(B, "\n")

print(A*B)

(3,)
[1 2 3] 

(1, 3)
[[1 2 3]] 

(3, 3)
[[1 1 1]
 [2 2 2]
 [3 3 3]] 

(3, 1, 3)
[[[1 1 1]]

 [[2 2 2]]

 [[3 3 3]]] 

[[[ 3  4  7]
  [ 5  0 -1]
  [ 2  1  5]]

 [[ 2  0 -2]
  [16  4  8]
  [10  4  2]]

 [[ 6  3  9]
  [ 3 27 12]
  [15 -6 12]]]


## Flatten and Reshape Arrays

In [28]:
A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

flatMatrix = A.flatten()
print(flatMatrix)

print(A.flatten(order="C"))
print(A.flatten(order="F"))
print(A.flatten(order="A"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [29]:
print(A.ravel())
print(A.ravel(order="A"))
print(A.ravel(order="F"))
print(A.ravel(order="A"))
print(A.ravel(order="K"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [31]:
X = np.array(range(24))
Y = X.reshape((3,4,2))
print(X)
print(Y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


## Concatening arrays

In [36]:
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])

print(np.concatenate((x,y,z)))

[11 22 18  7  6  1  3  5]


In [39]:
x = np.array(range(24))
x = x.reshape((3,4,2))
y = np.array(range(100,124))
y = y.reshape((3,4,2))
z = np.concatenate((x,y))
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]]

 [[100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[116 117]
  [118 119]
  [120 121]
  [122 123]]]


In [41]:
# changing axis
z = np.concatenate((x,y),axis = 1)
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]
  [100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]
  [108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]
  [116 117]
  [118 119]
  [120 121]
  [122 123]]]


## Vector Stacking

In [55]:
A = np.array([3, 4, 5])
B = np.array([1,9,0])

print(np.vstack((A, B)))
print(np.column_stack((A, B)))

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


In [59]:
A = np.array([[3, 4, 5],
              [1, 9, 0],
              [4, 6, 8]])
np.column_stack((A, A, A))

array([[3, 4, 5, 3, 4, 5, 3, 4, 5],
       [1, 9, 0, 1, 9, 0, 1, 9, 0],
       [4, 6, 8, 4, 6, 8, 4, 6, 8]])

## Repeting patterns with tile

In [60]:
x = np.array([ [1, 2], [3, 4]])
np.tile(x, (3,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])