In [31]:
import numpy as np

## Boolean Indexing

In [32]:
A = np.array([4, 7, 3, 4, 2, 8])

print(A == 4)

[ True False False  True False False]


In [33]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])

print(B>=42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [34]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])

B = A < 15
B.astype(np.int8)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]], dtype=int8)

## Fancy Indexing and Indexing with an Integer Array

In [35]:
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])

R = C[A<=5]
print(R)

[123 190 100]


In [36]:
C[[0, 2, 3, 1, 4, 1]]

array([123, 190,  99, 188,  77, 188])

## Nonzero and where

In [37]:
a = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])

print(a[a.nonzero()])
print(a.nonzero())
print(np.transpose(a.nonzero()))

[2 3 1 1 7 5 1]
(array([0, 0, 0, 1, 1, 2, 2]), array([1, 2, 4, 0, 3, 0, 3]))
[[0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [2 0]
 [2 3]]


In [38]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])

print(B >= 42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [39]:
import numpy as np

is_prime = np.ones((100,), dtype=bool)

is_prime[:2] = 0

nmax = int(np.sqrt(len(is_prime)))
for i in range(2, nmax):
    is_prime[2*i::i] = False

print(np.nonzero(is_prime))

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97]),)


# Vector Operations

In [40]:
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])

In [41]:
print( x + y )
print( x - y )
print( x * y )
print( x % y )

[8 9 3]
[-6  1  1]
[ 7 20  2]
[1 1 0]


## Dot Product

In [43]:
print(np.dot(x, y))
dot = np.dot(x ,y)
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus
angle = np.arccos(cos_angle)
angle

29


np.float64(0.860937724714075)

## Matrix Product

In [45]:
x = np.array( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
print(np.dot(x,y))

[[17  1]
 [28  1]]


In [47]:
x = np.array([0, 0, 1])
y = np.array([0, 1, 0])

print(np.cross(x, y))
print(np.cross(y, x))

[-1  0  0]
[1 0 0]
