In [14]:
import numpy as np

## Saving textfiles with savetxt

In [15]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]], np.int32)

# np.savetxt("arrays.txt", x)
np.savetxt("arrays.txt", x, fmt='%2.2f', delimiter=',')
# Complete sintax format
# savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')

## Loading Textfiles with loadtxt

In [16]:
y = np.loadtxt("arrays.txt", delimiter=",")
# y = np.loadtxt("arrays.txt", delimiter=",", usecols=(0,2))
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## tofile

In [29]:
dt = np.dtype([('time', [('min', int), ('sec', int)]), ('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10
x['temp'] = 98.25
print(x)

fh = open("test.txt", "bw")
x.tofile(fh)

[((10, 0), 98.25)]


## fromfile

In [27]:
# Sintax: numpy.fromfile(file, dtype=float, count=-1, sep='')
fh = open("arrays.txt", "rb")
np.fromfile(fh, dtype=dt)

array([((3471767528117644849, 3749862623231028272), 1.39737515e-76)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

## Best Practice to Load and Save Data

In [28]:
import numpy as np

print(x)

from tempfile import TemporaryFile

outfile = TemporaryFile()

x = np.arange(10)
np.save(outfile, x)

outfile.seek(0)
np.load(outfile)

[((10, 0), 98.25)]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## genfromtxt

In [32]:
sales = np.genfromtxt("arrays.txt", encoding='utf8', skip_header = 1, dtype=None)
sales

array(['4.00,5.00,6.00', '7.00,8.00,9.00'], dtype='<U14')