# 100 numpy exercises
https://www.kaggle.com/code/utsav15/100-numpy-exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print( np.__version__)
np.show_config()

2.3.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/marko/anaconda3/envs/numerical/include
    lib directory: /home/marko/anaconda3/envs/numerical/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/marko/anaconda3/envs/numerical/lib/pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /home/marko/anaconda3/envs/numerical/include
    lib directory: /home/marko/anaconda3/envs/numerical/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/marko/anaconda3/envs/numerical/lib/pkgconfig
    version: '2023.1'
Compilers:
  c:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/marko/anaconda3/envs/numerical/include,
      -fdebug-prefix-map=/croot/numpy_and_numpy_base_1750883793662/work=/usr/local/src/cond

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.array([1,2,3])
print("Memory size: ", array.size * array.itemsize)

Memory size:  24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
array = np.arange(10, 50)
array = array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
array = np.arange(0, 9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array = np.array( [1,2,0,0,4,0] )
new_array = np.array([])
for i1, val in enumerate(array):
    if val != 0:
        new_array = np.append(new_array, i1)
print(new_array)

print(array.nonzero())

[0. 1. 4.]
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
array = np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
array = np.random.random(9)
array

array([0.77511143, 0.75759262, 0.40283232, 0.10502122, 0.22854072,
       0.46683212, 0.9671589 , 0.53158808, 0.54314143])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
array = np.random.random((10,10))
print( array.min() )
print( array.max() )

0.020273808679190375
0.9939138551892369


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
array = np.random.random(30)
print(array.mean())

0.4559566923112016


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array = np.ones((10,10))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
print( 0 * np.nan )
print( np.nan == np.nan )
print( np.inf > np.nan )
print( np.nan - np.nan )
print( np.nan in set([np.nan]) )
print( 0.3 == 3 * 0.1 )

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
array = np.diag(1+np.arange(4),k=-1)
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
array = np.zeros((8,8))
array[::2, ::2] = 1
array[1::2, 1::2] = 1
array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [18]:
array = np.arange(6*7*8).reshape((6,7,8))
np.where(array == 100)

(array([1]), array([5]), array([4]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [19]:
array = np.zeros(8)
array[::2] = 1
array = np.tile(array, (8,1))
array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [20]:
array = np.array(range(25)).reshape(5,5)
array = array / np.sqrt( np.sum(array ** 2) )
print(array)

[[0.         0.01428571 0.02857143 0.04285714 0.05714286]
 [0.07142857 0.08571429 0.1        0.11428571 0.12857143]
 [0.14285714 0.15714286 0.17142857 0.18571429 0.2       ]
 [0.21428571 0.22857143 0.24285714 0.25714286 0.27142857]
 [0.28571429 0.3        0.31428571 0.32857143 0.34285714]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [21]:
dtype = np.dtype([
    ("red", "i4"),
    ("green", "i4"),
    ("blue", "i4"),
    ("alpha", "i4")
])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [22]:
array_1 = np.arange(5*3).reshape(5,3)
array_2 = np.arange(3*2).reshape(3,2)
np.dot(array_1, array_2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
array = np.arange(20).reshape(4,5)
array_new = array * ( np.logical_and(array > 3, array < 8) * -2 + 1 )
array_new

array([[ 0,  1,  2,  3, -4],
       [-5, -6, -7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))

In [24]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [25]:
z = np.array([1,2,3])
print(z**z)
print( 2 << z >> 2)
print( z <- z )
print(1j*z)
print(z/1/1)
# print(z<z>)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_16721/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_16721/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_16721/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [27]:
np.round(np.random.random(20) * 9 )

array([9., 1., 7., 7., 1., 5., 6., 8., 0., 5., 2., 2., 7., 1., 5., 5., 7.,
       3., 2., 2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
a = np.round( np.random.random(20) * 4 + 1 )
b = np.round( np.random.random(20) * 4 + 1 )
print(a[a == b])

[2.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [29]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_16721/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')
print(today, tomorrow, yesterday)

2025-09-14 2025-09-15 2025-09-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
array = np.arange(31)
today = np.datetime64('2025-07-01', 'D')
print( array + today )

['2025-07-01' '2025-07-02' '2025-07-03' '2025-07-04' '2025-07-05'
 '2025-07-06' '2025-07-07' '2025-07-08' '2025-07-09' '2025-07-10'
 '2025-07-11' '2025-07-12' '2025-07-13' '2025-07-14' '2025-07-15'
 '2025-07-16' '2025-07-17' '2025-07-18' '2025-07-19' '2025-07-20'
 '2025-07-21' '2025-07-22' '2025-07-23' '2025-07-24' '2025-07-25'
 '2025-07-26' '2025-07-27' '2025-07-28' '2025-07-29' '2025-07-30'
 '2025-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
array = np.array([[0,1,2,3,4]]*5) 
array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [34]:
np.random.random(10)

array([0.82134314, 0.06904006, 0.57447103, 0.09206443, 0.25688463,
       0.15860806, 0.82110475, 0.59040302, 0.96204917, 0.45730296])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [35]:
np.sort(np.random.random(10))

array([0.01678596, 0.05903776, 0.23016822, 0.33876637, 0.43623482,
       0.56358141, 0.70123595, 0.73270586, 0.86338166, 0.98167706])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [36]:
a = np.random.random(5)
b = np.random.random(5)
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [37]:
"""
a = np.random.random(10)
a.flags.writeable = False
a[1] = 2
"""

'\na = np.random.random(10)\na.flags.writeable = False\na[1] = 2\n'

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [38]:
array = np.random.random(20).reshape(10,2)
angle = np.arctan2(array[:,1],array[:,0])
r = np.sqrt( array[:,0] ** 2 + array[:,1] ** 2 )
np.round(np.vstack([r, angle]).T,2)

array([[1.1 , 0.82],
       [0.41, 0.75],
       [0.58, 0.43],
       [0.6 , 1.55],
       [1.03, 0.57],
       [0.92, 1.54],
       [1.02, 0.9 ],
       [0.68, 0.74],
       [0.61, 0.98],
       [1.05, 0.64]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [39]:
array = np.random.random(10)
array[ array == np.max(array) ] = 0
array

array([0.71663294, 0.79614305, 0.22428182, 0.67576982, 0.16263363,
       0.66314526, 0.72391786, 0.74644328, 0.        , 0.3399759 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [40]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [41]:
arr = np.random.random(10)
value = 10
arr[np.abs(np.min(arr - value)) == np.abs(arr - value)]

array([0.07415595])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [42]:
arr = np.random.random(100).reshape(50,2)
print(arr[:,0] - arr[:,1])

[ 0.62749706  0.04367406  0.5767947  -0.08217855  0.37058986  0.88927878
  0.1382645   0.75358306 -0.50977778  0.59647764 -0.03482955 -0.51145673
  0.44776732 -0.86461477 -0.19684402 -0.52046727  0.09178909 -0.429067
  0.86175704 -0.58866281 -0.05166068  0.54258704 -0.10451293  0.60437219
 -0.18462733 -0.83173892 -0.31211212 -0.25450399  0.21118166  0.74284806
  0.46554803 -0.38641067 -0.00636294  0.02421511 -0.27933144 -0.14188877
  0.57701732  0.18054245  0.78759781 -0.21124805 -0.072615   -0.27750477
  0.76282824 -0.61749117 -0.78327336 -0.66780139 -0.01107337 -0.38999527
  0.27512636 -0.1565893 ]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [43]:
a = np.round(10 * np.random.random((10,4)))
for ind, val in enumerate(a):
    a[ind] = a[ind] - np.mean(a[ind])
print(a)

[[-5.25  2.75 -0.25  2.75]
 [ 0.25  4.25 -2.75 -1.75]
 [-2.75  3.25  3.25 -3.75]
 [ 3.5  -3.5   1.5  -1.5 ]
 [-4.25 -2.25  2.75  3.75]
 [-1.5   1.5  -2.5   2.5 ]
 [ 1.25 -2.75  2.25 -0.75]
 [ 2.5  -1.5  -3.5   2.5 ]
 [-2.   -3.    2.    3.  ]
 [ 4.5  -2.5  -0.5  -1.5 ]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [44]:
a = np.random.random((10,10))
target = np.random.random()
b = (np.abs(a-target)) == np.min(np.abs(a - target))
a[b]

array([0.75805655])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [67]:
a = np.random.random((5,5))

def changerows(a, row1, row2):
    auxiliar = a[row1].copy()
    a[row1] = a[row2]
    a[row2] = auxiliar
    return a

print("Original matrix")
print(a)
print("New Matrix:")
print( changerows(a , 1, 2 ) )

Original matrix
[[0.40964033 0.38144174 0.25091483 0.08352382 0.75525967]
 [0.38681158 0.43320815 0.69253688 0.1803015  0.5833771 ]
 [0.93952911 0.69442723 0.65126375 0.07872296 0.39837523]
 [0.42772628 0.69862113 0.33660358 0.78912719 0.98792223]
 [0.96616857 0.4646581  0.89448625 0.62441787 0.42499577]]
New Matrix:
[[0.40964033 0.38144174 0.25091483 0.08352382 0.75525967]
 [0.93952911 0.69442723 0.65126375 0.07872296 0.39837523]
 [0.38681158 0.43320815 0.69253688 0.1803015  0.5833771 ]
 [0.42772628 0.69862113 0.33660358 0.78912719 0.98792223]
 [0.96616857 0.4646581  0.89448625 0.62441787 0.42499577]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [102]:
a = np.round( 10 * np.random.random((16,16)))
b = np.empty((4,4))

for i in range(0, 16, 4):
    for j in range(0, 16, 4):
        b[round(i/4),round(j/4)] = np.sum( a[i:i+4,j:j+4] )
        
print("Original 16x16 array: \n", a)
print("\nBlock-Sum 4x4 array: \n",b)

Original 16x16 array: 
 [[ 1.  2.  1.  7.  7.  5.  5.  5.  0.  4.  0.  7.  6.  1.  7.  2.]
 [ 1.  0.  6.  5.  5.  2.  4.  7.  8.  1.  6.  9.  4.  7.  5.  0.]
 [ 8.  3.  9.  2.  3.  6.  4. 10.  9.  1. 10.  3.  8.  1.  5.  5.]
 [ 1.  3.  6.  7.  2.  5.  6.  6.  7.  7.  3.  9.  2.  4.  1.  6.]
 [ 7.  8.  2.  9. 10.  1.  4.  8.  6.  1.  4.  6.  4.  5.  4.  6.]
 [ 8.  4.  3.  4.  6.  2.  3.  2.  4.  7.  4.  8.  2.  9.  7.  9.]
 [ 6.  7.  6.  7.  2.  8.  7.  3.  2.  9.  2.  3.  2.  2.  2.  3.]
 [ 3.  9. 10.  9.  5.  1. 10. 10.  2.  2.  4.  1.  9.  4.  0.  6.]
 [ 9.  5.  9.  7.  8.  6.  9.  7.  2.  8.  4.  6.  3.  0. 10.  1.]
 [ 7.  8.  0.  6.  7.  9.  3.  3.  2. 10.  0.  1.  0.  3.  8.  7.]
 [ 1.  5.  6.  9.  2.  7.  3. 10.  5.  8. 10.  7.  4.  8. 10.  1.]
 [ 2.  9.  6.  5.  6.  8.  7.  8.  4.  1.  7.  9.  1.  8.  1.  1.]
 [ 3.  5.  2. 10.  3.  7.  2.  7.  9. 10.  6.  1.  8.  9.  4.  4.]
 [ 7.  0.  4.  4.  6.  7.  3. 10.  7.  4.  3.  6.  5.  3.  8.  5.]
 [ 1.  0.  3.  4.  4.  4.  5.  9.  7. 

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [103]:
a = np.random.random((10,10))

def nlargestvalue(n):
    lista = []
    for i in range(n):
        lista.append(np.max(a))
        indice = np.where( a == np.max(a))
        a[indice[0], indice[1]] = -1
    return lista
    
answer = nlargestvalue(4)
print(answer)

[np.float64(0.9804802072232117), np.float64(0.9773823567381247), np.float64(0.9770203306928542), np.float64(0.9690578649610827)]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)