# 100 numpy exercises
https://www.kaggle.com/code/utsav15/100-numpy-exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print( np.__version__)
# np.show_config()

2.4.2


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.array([1,2,3])
print("Memory size: ", array.size * array.itemsize)

Memory size:  24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)
# np.info(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array = np.arange(10, 50)
array = array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array = np.arange(0, 9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [61]:
array = np.array([1,2,0,0,4,0])
for i1, val in enumerate(array):
    if val != 0:
        new_array = np.append(new_array, i1)
print(new_array)

print(array.nonzero())

[0. 1. 4.]
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
array = np.identity(3)
print(array)
print(np.eye(3))

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
array = np.random.random((3,3,3))
array

array([[[0.35358392, 0.87647374, 0.67282888],
        [0.40374161, 0.45316529, 0.47389617],
        [0.51157471, 0.77502466, 0.02138795]],

       [[0.62935421, 0.38340508, 0.69380181],
        [0.18719749, 0.71411433, 0.78438411],
        [0.05296305, 0.5261809 , 0.82092888]],

       [[0.9400031 , 0.39430987, 0.54892666],
        [0.03746267, 0.87175176, 0.05331691],
        [0.86447969, 0.50467203, 0.13297396]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
array = np.random.random((10,10))
print( array.min() )
print( array.max() )

0.006597364755425716
0.9970305049643333


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
array = np.random.random(30)
print(array.mean())

0.5357606809133522


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array = np.ones((10,10))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
array = np.arange(20).reshape((5,4))
array

def add_border( array ):
    (h, w) = array.shape
    y = np.zeros((1, w+2))

    new_array = y
    for i, value in enumerate(array):
        row = np.zeros((1, w+2))
        row[0, 1: w+1] = value
        new_array = np.concatenate((new_array, row)) 
    new_array = np.concatenate((new_array, y))
    return new_array

print(add_border(array))

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  3.  0.]
 [ 0.  4.  5.  6.  7.  0.]
 [ 0.  8.  9. 10. 11.  0.]
 [ 0. 12. 13. 14. 15.  0.]
 [ 0. 16. 17. 18. 19.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
print( 0 * np.nan )
print( np.nan == np.nan )
print( np.inf > np.nan )
print( np.nan - np.nan )
print( np.nan in set([np.nan]) )
print( 0.3 == 3 * 0.1 )

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
array = np.diag(1+np.arange(4),k=-1)
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
array = np.zeros((8,8))
array[::2, ::2] = 1
array[1::2, 1::2] = 1
array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
array = np.arange(6*7*8).reshape((6,7,8))
np.where(array == 100)

(array([1]), array([5]), array([4]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
array = np.array([[0,1],[1,0]])
array = np.tile(array, (4,4))
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
array = np.array(range(25)).reshape(5,5)
array = array / np.sqrt( np.sum(array ** 2) )
print(array)

[[0.         0.01428571 0.02857143 0.04285714 0.05714286]
 [0.07142857 0.08571429 0.1        0.11428571 0.12857143]
 [0.14285714 0.15714286 0.17142857 0.18571429 0.2       ]
 [0.21428571 0.22857143 0.24285714 0.25714286 0.27142857]
 [0.28571429 0.3        0.31428571 0.32857143 0.34285714]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
dtype = np.dtype([
    ("red", "i4"),
    ("green", "i4"),
    ("blue", "i4"),
    ("alpha", "i4")
])

array = np.array([(1,2,3,4),(10,11,12,13),(101,102,103,104)], dtype)
array['red']

array([  1,  10, 101], dtype=int32)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
array_1 = np.arange(5*3).reshape(5,3)
array_2 = np.arange(3*2).reshape(3,2)
np.dot(array_1, array_2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
array = np.arange(20).reshape(4,5)
array_new = array * ( np.logical_and(array > 3, array < 8) * -2 + 1 )
array_new

array([[ 0,  1,  2,  3, -4],
       [-5, -6, -7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))

In [25]:
sum(range(5),-1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
z = np.array([1,2,3])
print(z**z)
print( 2 << z >> 2)
print( z <- z )
print(1j*z)
print(z/1/1)
# print(z<z>)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_22997/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_22997/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_22997/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
np.round(np.random.random(20) * 9 )

array([9., 3., 7., 9., 5., 3., 9., 3., 7., 1., 0., 3., 2., 3., 7., 2., 6.,
       6., 3., 8.])

#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
a = np.round( np.random.random(20) * 4 + 1 )
b = np.round( np.random.random(20) * 4 + 1 )
print(a[a == b])

[2. 5. 2. 2. 2. 2. 3.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_22997/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')
print(today, tomorrow, yesterday)

2026-03-18 2026-03-19 2026-03-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
array = np.arange(31)
today = np.datetime64('2025-07-01', 'D')
print( array + today )

['2025-07-01' '2025-07-02' '2025-07-03' '2025-07-04' '2025-07-05'
 '2025-07-06' '2025-07-07' '2025-07-08' '2025-07-09' '2025-07-10'
 '2025-07-11' '2025-07-12' '2025-07-13' '2025-07-14' '2025-07-15'
 '2025-07-16' '2025-07-17' '2025-07-18' '2025-07-19' '2025-07-20'
 '2025-07-21' '2025-07-22' '2025-07-23' '2025-07-24' '2025-07-25'
 '2025-07-26' '2025-07-27' '2025-07-28' '2025-07-29' '2025-07-30'
 '2025-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
A = np.array([20,20,20,20])
B = np.array([1,2,3,4])

np.add(A, B, out=B)
np.multiply(B, -A*2, out=B)
B

array([-840, -880, -920, -960])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
array = np.random.random((1,4))*10
print(array)
print(np.floor(array))
print(np.trunc(array))
print(array.astype(int))
print(array // 1)

[[2.76151372 2.22741278 7.344714   2.69042154]]
[[2. 2. 7. 2.]]
[[2. 2. 7. 2.]]
[[2 2 7 2]]
[[2. 2. 7. 2.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
array = np.array([[0,1,2,3,4]]*5) 
array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
def genInt():
    i = 1
    while i<=10:
        yield i
        i+=1

array = np.fromiter(genInt(), int)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
np.random.random(10)

array([0.65698984, 0.73423126, 0.1028221 , 0.48531008, 0.06629132,
       0.24246426, 0.01612955, 0.30174687, 0.52374587, 0.30875031])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
np.sort(np.random.random(10))

array([0.00897412, 0.2927576 , 0.36663389, 0.38699821, 0.50140579,
       0.60569021, 0.64327154, 0.67492584, 0.74057223, 0.86956205])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [40]:
import time
array = []
for a in range(1000000): array.append(a)

inicio = time.perf_counter()
np.sum(array)
fin = time.perf_counter()
print(f"execution time {fin - inicio}")

inicio = time.perf_counter()
sum(array)
fin = time.perf_counter()
print(f"execution time {fin - inicio}")

execution time 0.03722308799842722
execution time 0.006831658000010066


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [41]:
a = np.random.random(5)
b = np.random.random(5)
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [42]:
a = np.random.random(10)
a.flags.writeable = False
# a[1] = 2

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [43]:
np.random.seed(5)
array = np.random.randint(1, 20, (10,2))

x, y = array[:, 0], array[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

np.column_stack((r, theta))

array([[15.5241747 ,  1.31019394],
       [17.4642492 ,  0.41241044],
       [19.72308292,  0.53172407],
       [10.29563014,  0.5070985 ],
       [18.78829423,  1.13095374],
       [18.78829423,  0.43984258],
       [20.61552813,  0.88847977],
       [19.6977156 ,  0.41822433],
       [21.40093456,  0.65284663],
       [18.43908891,  0.70862627]])

In [44]:
np.random.seed(5)
array = np.random.randint(1, 20, (10,2))
angle = np.arctan2(array[:,1],array[:,0])
r = np.sqrt( array[:,0] ** 2 + array[:,1] ** 2 )
np.round(np.vstack([r, angle]).T,2)

array([[15.52,  1.31],
       [17.46,  0.41],
       [19.72,  0.53],
       [10.3 ,  0.51],
       [18.79,  1.13],
       [18.79,  0.44],
       [20.62,  0.89],
       [19.7 ,  0.42],
       [21.4 ,  0.65],
       [18.44,  0.71]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
np.random.seed(12)
array = np.random.random(10)
array[ array == np.max(array) ] = 0
print(array)

np.random.seed(12)
array = np.random.random(10)
indMax = array.argmax()
array[indMax] = 0
print( array )

[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496 0.91874701
 0.90071485 0.03342143 0.         0.13720932]
[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496 0.91874701
 0.90071485 0.03342143 0.         0.13720932]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [46]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [47]:
arr = np.random.random(10)
value = 10
min = arr[np.abs(np.min(arr - value)) == np.abs(arr - value)]
print(arr)
print(min)

[0.28382835 0.60608318 0.94422514 0.85273554 0.00225923 0.52122603
 0.55203763 0.48537741 0.76813415 0.16071675]
[0.00225923]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [48]:
dtype = np.dtype([
    ('coords', [('x', 'i4'), ('y', 'i4')]), 
    ('color',  [('r', 'i8'), ('g', 'i8'), ('b', 'i8')])
])

array = np.array( [
    ((4,4), (1,1,1)),
    ((2,2), (-1,-1,-1)),
    ((10,10), (5,5,5))
], dtype)

array['coords']
array['coords']['x']

array([ 4,  2, 10], dtype=int32)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [49]:
arr = np.random.random(5*2).reshape(5,2)
x, y = arr[:, 0], arr[:, 1]
distances = x - y
distances[:, np.newaxis] - distances[np.newaxis, :]

array([[ 0.        ,  0.72481349,  1.10530571,  1.08868917,  1.18728985],
       [-0.72481349,  0.        ,  0.38049222,  0.36387568,  0.46247636],
       [-1.10530571, -0.38049222,  0.        , -0.01661654,  0.08198413],
       [-1.08868917, -0.36387568,  0.01661654,  0.        ,  0.09860067],
       [-1.18728985, -0.46247636, -0.08198413, -0.09860067,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [50]:
arr = np.array( [1,2,3,4,5], dtype=np.float32)
arr = arr.astype(np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [58]:
# np.genfromtxt( 'file.txt', delimiter=',' )

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [51]:
array = np.floor(np.random.random(4*5).reshape((4,5)) * 1000).astype(int)

for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 702
(0, 1) 327
(0, 2) 334
(0, 3) 978
(0, 4) 624
(1, 0) 950
(1, 1) 767
(1, 2) 825
(1, 3) 406
(1, 4) 451
(2, 0) 400
(2, 1) 995
(2, 2) 177
(2, 3) 962
(2, 4) 419
(3, 0) 424
(3, 1) 463
(3, 2) 373
(3, 3) 465
(3, 4) 35


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [52]:
a = np.round(10 * np.random.random((10,4)))
for ind, val in enumerate(a):
    a[ind] = a[ind] - np.mean(a[ind])
print(a)

[[-2.5   3.5   2.5  -3.5 ]
 [ 0.25 -0.75 -1.75  2.25]
 [-0.5  -4.5   1.5   3.5 ]
 [-2.75 -0.75  2.25  1.25]
 [-1.25 -1.25  2.75 -0.25]
 [ 0.   -2.   -1.    3.  ]
 [-2.5   4.5  -3.5   1.5 ]
 [-5.5   1.5   0.5   3.5 ]
 [ 1.75 -3.25 -0.25  1.75]
 [ 2.25 -0.75 -0.75 -0.75]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [53]:
a = np.random.random((10,10))
target = np.random.random()
b = (np.abs(a-target)) == np.min(np.abs(a - target))
a[b]

array([0.77494022])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [54]:
array = np.arange(5*5*3).reshape((5,5,3))
kernel = np.arange(5*5).reshape((5,5))
kernel = kernel[:, :, np.newaxis]

print(array, '\n')
print(kernel, '\n')
print(array * kernel)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]] 

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]
  [24]]] 

[[[   0    0    0]
  [   3    4    5]
  [  12   14   16]
  [  27   30   33]
  [  48   52   56]]

 [[  75   80   85]
  [ 108  114  120]
  [ 147  154  161]
  [ 192  200  208]
  [ 243  252  261]]

 [[ 300  310  320]
  [ 363  374  385]
  [ 432  444  456]
  [ 507  520  533]
  [ 588  602  616]]

 [[ 675  690  705]
  [ 768  784  800]
  [ 867  884  901]
  [ 972  990 1008]
  [1083 1102 1121]]

 [[1200 1220 1240]
  [1323 1344 1365]
  [1452 1474 1496]
  [1587 1610 1633]
  [1728 1752

#### 72. How to swap two rows of an array? (★★★)

In [55]:
a = np.random.random((5,5))

def changerows(a, row1, row2):
    auxiliar = a[row1].copy()
    a[row1] = a[row2]
    a[row2] = auxiliar
    return a

print("Original matrix")
print(a)
print("New Matrix:")
print( changerows(a , 1, 2 ) )

Original matrix
[[0.25981749 0.63891307 0.82679998 0.52130526 0.42448514]
 [0.53100304 0.94597812 0.99927366 0.67092359 0.78957614]
 [0.98158755 0.14155841 0.02628702 0.74644276 0.61658807]
 [0.0992047  0.52190268 0.50743198 0.28569303 0.24843849]
 [0.18034918 0.58382307 0.15391861 0.71172759 0.85875241]]
New Matrix:
[[0.25981749 0.63891307 0.82679998 0.52130526 0.42448514]
 [0.98158755 0.14155841 0.02628702 0.74644276 0.61658807]
 [0.53100304 0.94597812 0.99927366 0.67092359 0.78957614]
 [0.0992047  0.52190268 0.50743198 0.28569303 0.24843849]
 [0.18034918 0.58382307 0.15391861 0.71172759 0.85875241]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [56]:
a = np.round( 10 * np.random.random((16,16)))
b = np.empty((4,4))

for i in range(0, 16, 4):
    for j in range(0, 16, 4):
        b[round(i/4),round(j/4)] = np.sum( a[i:i+4,j:j+4] )
        
print("Original 16x16 array: \n", a)
print("\nBlock-Sum 4x4 array: \n",b)

Original 16x16 array: 
 [[ 7.  3.  4.  5.  3.  5.  7.  3.  2.  8.  8.  0.  6.  1.  5.  3.]
 [ 8.  1.  9.  3.  1.  5.  1.  7.  4.  3.  1.  2.  5.  1.  5.  9.]
 [ 4.  2.  8.  7.  6.  1.  4.  5.  4.  2.  2.  1.  7.  1.  3.  4.]
 [ 0.  2.  2.  8.  2.  7.  3.  7.  7.  2.  4.  7.  6.  6.  0.  9.]
 [ 9.  2.  4.  9.  5.  4.  7.  2.  9.  0.  1.  4.  2.  5.  1.  6.]
 [ 5.  8.  3.  2.  5.  2.  5.  1.  6.  8.  9. 10.  6.  5.  8.  7.]
 [ 2.  4.  2.  6.  5.  5. 10.  9.  2.  6.  5.  8.  9.  8.  0.  9.]
 [ 2.  3.  4.  8.  2.  2. 10.  0.  3.  4.  2.  3.  1.  8.  2.  6.]
 [ 4.  0.  2.  8.  4.  1. 10.  7.  7.  9.  9.  9.  4.  3.  5.  8.]
 [ 5.  4.  6.  6. 10.  6.  4.  9.  7.  4.  5. 10. 10.  0.  8.  4.]
 [ 4.  3.  6.  2.  2.  2.  6.  1.  3.  8.  5. 10.  7.  1.  4.  5.]
 [ 9.  9.  1.  9.  7.  6.  9.  4.  7.  8.  8.  6.  6.  9.  2.  7.]
 [ 8.  1.  8.  1.  1.  5.  9.  9.  6.  8.  3.  6.  2.  3.  9.  9.]
 [ 7.  5.  9.  2.  5.  6.  0.  8.  3.  9.  9.  8.  8.  3.  2.  4.]
 [ 4.  9.  8.  8.  7.  8.  5.  9. 10. 

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [57]:
a = np.random.random((10,10))

def nlargestvalue(n):
    lista = []
    for i in range(n):
        lista.append(np.max(a))
        indice = np.where( a == np.max(a))
        a[indice[0], indice[1]] = -1
    return lista
    
answer = nlargestvalue(4)
print(answer)

[np.float64(0.9997419299050934), np.float64(0.9987123114553902), np.float64(0.9494186141113726), np.float64(0.9477711632499198)]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)