In [1]:
import numpy as np
import matplotlib.pyplot as plt

## ELimintation from A to U

In [54]:
def gaussian(A, b):
    C = np.concatenate((A, b[:, np.newaxis]), axis=1)
    
    for j in range(len(C[0,:])):
        for i in range(len(C)):
            if i >= j:
                if C[i,j] == 0 and i < len(C)-1 and i == j :
                    C[[i, i+1]] = C[[i+1, i]]
                if C[i,j] != 0 and i != j:
                    C[i,:] = C[i,:] - C[j,:] * ( C[i,j] / C[j,j] )
                    
    return C

In [55]:
A = np.array([[2,4,-2], [4,0,-3], [-2,-3,7]], dtype=np.longdouble)
b = np.array([2,8,10])

print ( gaussian( A, b ) )

[[ 2.     4.    -2.     2.   ]
 [ 0.    -8.     1.     4.   ]
 [ 0.     0.     5.125 12.5  ]]


## Elimination Matrix and Row Exchange Matrix

In [56]:
matrix = np.array([[2,4,-2],[4,9,-3],[-2,-3,7]])

elimination = np.array([[1,0,0],[-2,1,0],[0,0,1]])
rowexchange = np.array([[1,0,0],[0,0,1],[0,1,0]])
augmented = np.array([2,8,10])

In [57]:
print("\nOriginal:\n", matrix)
print("\nElimination:\n", elimination @ matrix)
print("\nElimination:\n", rowexchange @ matrix)
print("\nAugmented matrix:\n", np.concatenate((matrix, augmented[:,np.newaxis]), axis=1))


Original:
 [[ 2  4 -2]
 [ 4  9 -3]
 [-2 -3  7]]

Elimination:
 [[ 2  4 -2]
 [ 0  1  1]
 [-2 -3  7]]

Elimination:
 [[ 2  4 -2]
 [-2 -3  7]
 [ 4  9 -3]]

Augmented matrix:
 [[ 2  4 -2  2]
 [ 4  9 -3  8]
 [-2 -3  7 10]]


## Inverse Matrix

### $A^-1$ exists if $A$ has a full set of $n$ pivots

In [73]:
def inverse(A):
    n = np.shape(A)
    for j in range(len(A[0,:])):
        for i in range(len(A)):
            if ( j <= np.shape(A)[0]-1 ):
                if A[i,j] != 0 and i==j :
                    A[i,:] = A[i,:] / A[i,i] 
                elif A[i,j] != 0 :
                    A[i,:] = A[i,:] - A[j,:] * ( A[i,j] / A[j,j] )
    return A, n

In [91]:
A = np.array([[2,4,-2], [4,9,-3], [-1,-3,7]], dtype=np.longdouble)
b = np.array(np.eye(np.shape(A)[0]))
c = np.concatenate((A, np.eye(np.shape(A)[0])), axis=1)

print("A: \n", A, "\n")
print("Original Augmented matrix: \n", c, "\n")
print("Reduced Row Echelon Form:")
print(inverse(c)[0] )
print("\nInverse matrix:" )
print(inverse(c)[0][:,inverse(c)[1][0]:] )
print("\nMultiplying A by A^-1\n", np.round(A @ inverse(c)[0][:,inverse(c)[1][0]:]) )

A: 
 [[ 2.  4. -2.]
 [ 4.  9. -3.]
 [-1. -3.  7.]] 

Original Augmented matrix: 
 [[ 2.  4. -2.  1.  0.  0.]
 [ 4.  9. -3.  0.  1.  0.]
 [-1. -3.  7.  0.  0.  1.]] 

Reduced Row Echelon Form:
[[ 1.          0.          0.          3.85714286 -1.57142857  0.42857143]
 [ 0.          1.          0.         -1.78571429  0.85714286 -0.14285714]
 [ 0.          0.          1.         -0.21428571  0.14285714  0.14285714]]

Inverse matrix:
[[ 3.85714286 -1.57142857  0.42857143]
 [-1.78571429  0.85714286 -0.14285714]
 [-0.21428571  0.14285714  0.14285714]]

Multiplying A by A^-1
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## LU factorization

In [100]:
def ldu( matrix ):
    l = np.eye(np.shape(matrix)[0])
    u = matrix.copy()
    d = np.zeros((np.shape(matrix)[0], np.shape(matrix)[0]), dtype=np.float64)
    
    for j in range(len(matrix[0,:])):
        for i in range(len(matrix)):
             if ( i >= j  ): 
                if u[i,j] != 0 and i != j :
                    factor = u[i,j] / u[j,j]
                    u[i,:] = u[i,:] - u[j,:] * ( factor )
                    l[i,j] = factor

    for i in range(np.shape(l)[0]):
        d[i,i] = u[i,i]
        u[i,:] = u[i,:] / u[i,i]
        
    return np.round(l, 2), np.round(d, 2), np.round(u, 2)

In [101]:
matrix = np.array([[1,2],[3,4]])
matrix = np.array(([[2,1,0], [1,2,1], [0,1,2]]), dtype=np.float64)
matrix = np.array([[1,1,1,1], [1,2,3,4], [1,3,6,10], [1,4,10,20]], dtype=np.float64)

print( "Original matrix:\n", matrix )
print( "\nL:\n",ldu(matrix)[0] )
print( "\nD:\n",ldu(matrix)[1] )
print( "\nU:\n",ldu(matrix)[2] )
print( "\n LDU\n", ldu(matrix)[0] @ ldu(matrix)[1] @ ldu(matrix)[2] )

Original matrix:
 [[ 1.  1.  1.  1.]
 [ 1.  2.  3.  4.]
 [ 1.  3.  6. 10.]
 [ 1.  4. 10. 20.]]

L:
 [[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 1. 0.]
 [1. 3. 3. 1.]]

D:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

U:
 [[1. 1. 1. 1.]
 [0. 1. 2. 3.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]

 LDU
 [[ 1.  1.  1.  1.]
 [ 1.  2.  3.  4.]
 [ 1.  3.  6. 10.]
 [ 1.  4. 10. 20.]]


## Transposes and Permutations

Sum $ (A+B)^T = A^T + B^T$

Product $ (AB)^T = B^TA^T $

Inverse $ (A^{-1})^T = (A^T)^{-1}$

Inside: The dot product or inner product is $x^Ty$ $\hspace{2cm}$ $(1 \times n)(n \times 1)$

Outside: The rank one product or outer product is $xy^T$ $\hspace{0.7cm}$ $(n \times 1)(1 \times n)$

## Symetric matrices

if a matrix is symmetric then L = U^-1 

In [123]:
def is_symmetric(matrix):
    return not (False in (matrix == matrix.T))

def convert_matrix(matrix, sideT="l"):
    if sideT == "l":
        return np.array(matrix).T @ np.array(matrix)
    elif sideT == "r":
        return np.array(matrix) @ np.array(matrix).T

In [124]:
a = np.array([[1,2],[2,1]])
b = np.array([[1,2,3], [4,5,6]])

print( convert_matrix(b, "r") )
print( is_symmetric(convert_matrix(b, "r")) )

print( convert_matrix(b, "l") )
print( is_symmetric(convert_matrix(b, "l")) )

[[14 32]
 [32 77]]
True
[[17 22 27]
 [22 29 36]
 [27 36 45]]
True
